### ISSUE TITLE
Research alternatives to webpack

### ISSUE THREAD

**Issue by mhines-usgs** [usgs-makerspace/wbeep-viz#1]
Talk to Mary and decide if we need a meeting about this with all of us or who
IoW is using Babel and others

**Comment by abriggs-usgs** [comment]
Did a preliminary chat with Mary. She recommended Rollup as an ES6 compiler. Also outside of the Webpack question, we should add Codacy code checking and Travis build checking to the repository.

**Comment by abriggs-usgs** [comment]
JavaScript Setup and Tooling
Google Doc: https://docs.google.com/document/d/1wCc8BHd2pgYCVKnHtmDmw0IAwewxVyyvft9LzkSuVjw/edit?usp=sharing

What follows is a rough set of notes that can be used as a guide for further discussions on JavaScript build tooling. 

Summary
There has been many changes and advances in JavaScript build tooling in the last several years. Other front-end projects in the Water Mission Area have successfully used a wide array of build tools that offer a good base for judgment about a given tool’s value and ease of use.
Using this experience base and research from the internet, I suggest attempting to use Vue as a framework for new projects. The Vue framework uses many of the same build tools that have been tested in other projects all bundled in an easy to build package. Using the Vue framework will require an investment in time to learn but will significantly reduce the knowledge needed to use and integrate a hodgepodge of random and unintegrated build tools.   

General notes:
Good Overview Article on JavaScript Build Tooling
https://medium.com/the-node-js-collection/modern-javascript-explained-for-dinosaurs-f695e9747b70

Repository Tooling - These tools aid developers by automating the process of checking code consistency and project build viability. Both have been used on other projects in the WMA and are highly recommended.  

Codacy 
Travis


Modules - Modules are part of all modern JavaScript builds and require Node JS. Not that knowledge of Node JS is not required beyond the ability to install Node JS a the host system.

Node Js - required to run NPM and for use in module packaging (requires file system access)


Package Management - Package management is also a requirement of modern JavaScript applications. There are two main choices, Node Package Manager (NPM) and Yarn. Several years ago, Yarn was a superior choice due to the ability to commit dependency version numbers to source code management. Node Package Manager now has this capability. Additionally, NPM also has an integrated development server with ‘hot load’ and task runner ability.

****NPM (more users, task runner, development server)
Yarn (created package-lock, but now NPM has that too)

Module Bundlers - needed to use the modules in a browser allows use of import and require statements
Here’s a good overview: https://medium.com/js-imaginea/comparing-bundlers-webpack-rollup-parcel-f8f5dc609cfd

There are four main choices here, with Parcel being the newest and fastest, and Browserify being the most mature. Webpack is full featured but heavy in terms of build times and learning to use. Rollup is lighter than Webpack in both learning curves and build times. Rollup is now used in many major internet applications such as Facebook. This area doesn’t have an obvious winner. We have a knowledge/experience pool for Webpack and Rollup, but Parcel is a fast and tempting option. 

**Webpack 4 (more unified development but harder to use)
**Rollup (used in waterdata_ui and ngwmn_ui, fast build time, moderate configuration)
**Parcel (newest, easiest to configure)
Browserify (older works well with grunt)


Transpilers - used to convert ES6+ code into a form readable by modern browsers.
Babel is a tried and true performer here, but Buble is faster. Both have been used in previous WMA projects and Buble is the current preference. 

Babel
****Buble (newer then Babel)


Task Runners - used to automate the steps required to complete a project build. 
 
A comparison between several task runners: https://www.toptal.com/front-end/webpack-browserify-gulp-which-is-better

All of the listed task runners have seen use in WMA projects, the current favorite is Node Package Manager. The main advantage here is ease of configuration through package.json and since NPM is already the recommended choice for package management, using it means one less project dependency. 

****NPM (added new features, now has task runners built in)
Gulp (task or build runner)
Grunt (considered outdated when compared with Gulp, but easier to understand)


Other Considerations

Frameworks - bundle many of the needed build tools into a neat and tidy package, also aid in creating a consistent application architecture. 

As these are big topics, I only dug deeply into Vue. Angular, I dismissed as too encompassing for our needs. Angular is also an aging technology with a steep learning curve that perhaps is not worth the time investment. React is newer than Angular and has many components that would match our needs, however, like Angular learning, React is said to be intensive. Vue is the newest framework and many claim it blends the best of both React and Angular while still being relatively easy to learn. Additionally, the user documentation for Vue is noted to be thorough and easy to understand. 
	In short using a framework would take the sting out of the JavaScript build process. Vue in particular has extremely straightforward configuration. In Vue, it as simple as a few clicks to completely setup the build tools and run a project. 
 
Vue
	Has many of the build tools included
	Has unit testing framework 
	SASS preprocessor
	Code Linting
	Built in state management with ‘vuex’
	Has easy setup with Vue CLI and has an optional graphic interface, vue ui
	Good Tutorial: https://www.youtube.com/watch?v=Wy9q22isx3U
React
Angular

Testing, assertion libraries and test runners - needed to support application code changes and provide some assurance that new code flaws are not introduced. 

The setup of test suites are fairly complex and include multiple components -- tests, test runners, and assertion libraries. Vue includes built in setup for Jest and Mocha. It also has access to ‘plug-ins’ for many other offerings. 
   
Vue has the unit test suites of Jasmine/Jest and Mocha/Chai built in,as well as End to End testing
Jasmine (testing, used in waterdata_ui (WDFN) and NGWMN)
Karma (test runner used with Karma in the same projects as above)
Mocha doesn’t have a built in assertion library; there are several options
Assertion libraries - Chai, should.js, expect.js, and better-assert


USWDS (United States Web Design System) - a comprehensive system providing 508 compliant color palates and layout tools.

Using the design system will require and investment in learning time, but it will lessen the load when it comes to basic component design, accessibility compliance, responsive design, and color coherence across projects. The USWDS design system can be added to the project as NPM package. 
In addition to the USWDS, the USGS now has standard components to include such as the Regulation USGS headers and footers. These are available to projects by importing the wdfn-vis package through NPM. I am not sure how compatible the wdfn-vis package is with Vue as I don’t fully understand the way that the variable for assets path is being populated. But I am guessing that this is not insurmountable.  

Language preprocessors - used to convert more complex styling languages back into standard CSS. 

SASS is the current standard. Vue has the ability to add the tooling required for various preprocessors. Other WMA projects have used node-SASS, dart-SASS is a newer product that claims faster processing.  

SASS (node-SASS, dart-SASS)
JSX (only with react)
On adding styles to Vue: https://dev.to/lynnewritescode/my-scss-setup-within-a-vue-cli-3-project-4jan


Templating engines - used to allow variable substitution in HTML code
There are numerous templating engines available. The ones used in the Water Data for the Nation monitoring location pages use Jinja2, other WMA application have used Handlebars. The Vue framework has a templating engine built in.

Vue has this built in
Jinja2 (used in waterdata_ui and NGWMN, written in Python)
Handlebars (used in Publication Warehouse)

Page Routing - used with single page applications to allow the URL to appear like that of a standard webpage. Also allows users to access various content contained in single page applications through the URL as if the content were on separate pages.

In other WMA applications Flask was used to accomplish URL routing. Flask is written using Python. Vue has page routing capacity built in using JavaScript. Using Vue would eliminate the need for Python knowledge. 

Vue has page routing built in
Flask (used in waterdata_ui and NGWMN, written in Python)
