### ISSUE TITLE
Add mapbox hover effect over HRUs

### ISSUE THREAD

**Issue by mhines-usgs** [usgs-makerspace/wbeep-viz#22]
We will drop the outlines of the HRU and add a hover effect that pops the polygon out when a mouse is above it - https://docs.mapbox.com/mapbox-gl-js/example/hover-styles/

**Comment by mhines-usgs** [comment]
We briefly chatted about this in the technical meeting today - 

- [ ] make the hover effect change the outline to a bright contrasting color to the original color of the polygon

Aaron pointed out that this effect will not work on mobile, since there is no sense of hover, FYI.

**Comment by abriggs-usgs** [comment]
Pull Request  - https://github.com/usgs-makerspace/wbeep-viz/pull/48

This adds an opacity change to highlight the Hydrological Response Unit (HRU). This a imperfect solution. While it does highlight the HRU, it changes the color which may be significant to the user.

Highlighting the boundary of the HRU is not possible without changes to the tiles. Since the HRUs share boundaries, only part of the boundary of each HRU shows. The code change required to highlight the HRUs in the Vue portion of the application is trivial.

**Comment by abriggs-usgs** [comment]
For Review: The hover effect is active on the test URL: http://wbeep-test-website.s3-website-us-west-2.amazonaws.com/

Checkout and please add any comments or thoughts you have.

**Comment by lindsayplatt** [comment]
I think we talked about trying out the 3D effect instead of the white highlight?

**Comment by abriggs-usgs** [comment]
I thought I made a new issue for that. I will investigate and make a new issue if necessary.

**Comment by abriggs-usgs** [comment]
Okay, yup. I failed to add the new issue previously, but that is now fixed.

Here is the new issue, https://github.com/usgs-makerspace/makerspace-sandbox/issues/144 .

**Comment by lindsayplatt** [comment]
Since there is a new issue. This can be closed.
