### ISSUE TITLE
Discuss with Shawn the control of access to the buckets

### ISSUE THREAD

**Issue by mhines-usgs** [usgs-makerspace/wbeep-viz#39]
Are there any issues with opening up the tiles in s3 to anyone anywhere?

Possible concerns about bandwidth costs, however Ivan has mentioned that cost to use s3 is very negligible.

**Comment by lindsayplatt** [comment]
What are the pros of allowing this? What are the cons? (From our perspective, not including cost)

**Comment by abriggs-usgs** [comment]
I had a discussion with Shawn about this. 

Basically, he said it will be possible to allow only our applications to have access to any web host bucket by adjusting the 'bucket policy' as long as those buckets are not publicly accessible through CloudFront. That is to say, we can host our background layers in a bucket using just the standard bucket URL, like http://wbeep-test-website.s3-website-us-west-2.amazonaws.com/ . Shawn mentioned that he could also use some 'cert' magic to get a our layer hosting bucket a HTTPS connection (normally this is only possible using CloudFront). He said that the buckets with content distributed through CloudFront are by their nature publicly accessible, because of that, he said it would be hard to control access.  The draw back of this is that we won't have the high speed cache that Cloudfront provides when serving the tiles. Whether is will be a problem remains to be seen. 

Cost wise, hosting even a large tile sets (~150 GB) would be relatively small (according to the Amazon doc - less than $10 a month), which is far less than the cost of hosting on our own infrastructure. Shawn didn't give any exact numbers for the cost but described it as 'minimal'.

Summary
Yes, we can host huge tile sets on S3
No, we can't (probably) use CloudFront (no fast cache, or pretty URLs)
The cost is low and the maintenance is zip.

**Comment by abriggs-usgs** [comment]
Okay, after David pointed out the applications we will use to call for tiles are client-side not server-side (duh). I contacted Shawn again. He said that there is no real way to control access to the bucket and still allow use on public computers. However, he also didn't seem to feel that it was a risk to leave it open since the content is neither secret or of monetary value and the bucket was basically acting like a regular website, which is also open to the public.
